#!/usr/bin/env python3

import os
import glob
import envtpl
from configparser_extended import ExtendedConfigParser

MFSERV_PLUGINS_HOME = os.path.join(os.environ["MODULE_RUNTIME_HOME"],
                                   "var", "plugins")
LOG_LEVEL = os.environ.get('MFSERV_LOG_MINIMAL_LEVEL', 'INFO')
CONFIG = os.environ.get('MFCONFIG', 'GENERIC')
MODULE_RUNTIME_HOME = os.environ["MODULE_RUNTIME_HOME"]
MODULE_HOME = os.environ["MODULE_HOME"]

'''
Below are defined process types depending on the code language
'''

# Available types for watching python (i.e gunicorn)
PYTHON_TYP_LIST = [
    "gunicorn3_sync",
    "gunicorn2_sync",
    "gunicorn3_asyncio"
]

# Available types for watching js (i.e node)
JS_TYP_LIST = [
    "node"
]

# All types
ALL_TYP_LIST = \
    PYTHON_TYP_LIST + \
    JS_TYP_LIST


def make_watcher_conf(plugin_configuration_file):
    output = []
    parser = ExtendedConfigParser(config=CONFIG, strict=False,
                                  inheritance='im', interpolation=None)
    plugin_name = os.path.basename(os.path.dirname(plugin_configuration_file))
    plugin_dir = os.path.dirname(plugin_configuration_file)
    parser.read(plugin_configuration_file)
    apps = [x.replace("app_", "", 1).split(':')[0] for x in parser.sections()
            if x.startswith("app_")]
    extra_daemons = [x.replace("extra_daemon_", "", 1).split(':')[0]
                     for x in parser.sections()
                     if x.startswith("extra_daemon_")]
    os.environ["MFSERV_CURRENT_PLUGIN_DIR"] = \
        "%s/%s" % (MFSERV_PLUGINS_HOME, plugin_name)

    redis_service = False
    if parser.has_option("general", "redis_service"):
        redis_service = parser.getboolean("general", "redis_service")

    # gunicorn_log_level
    gunicorn_log_level = LOG_LEVEL.lower()
    if gunicorn_log_level not in ('debug', 'info', 'warning', 'error',
                                  'critical'):
        gunicorn_log_level = "debug"

    for app in apps:
        section = "app_%s" % app
        typ = parser.get(section, "type")
        if typ not in ALL_TYP_LIST:
            continue

        if typ in PYTHON_TYP_LIST:
            gunicorn_arg = parser.get(section, "gunicorn_arg")

            add_plugin_dir_to_python_path = True
            if parser.has_option(section, "add_plugin_dir_to_python_path"):
                add_plugin_dir_to_python_path = \
                    parser.getboolean(section, "add_plugin_dir_to_python_path")

            add_app_dir_to_python_path = False
            if parser.has_option(section, "add_app_dir_to_python_path"):
                add_app_dir_to_python_path = \
                    parser.getboolean(section, "add_app_dir_to_python_path")

        elif typ in JS_TYP_LIST:
            node_arg = parser.get(section, "node_arg")

            add_plugin_dir_to_node_path = True
            if parser.has_option(section, "add_plugin_dir_to_node_path"):
                add_plugin_dir_to_node_path = \
                    parser.getboolean(section, "add_plugin_dir_to_node_path")

            add_app_dir_to_node_path = False
            if parser.has_option(section, "add_app_dir_to_node_path"):
                add_app_dir_to_node_path = \
                    parser.getboolean(section, "add_app_dir_to_node_path")

        workers = parser.get(section, "workers")

        rlimit_as = None
        rlimit_nofile = None
        rlimit_nproc = None
        rlimit_stack = None
        rlimit_core = None
        rlimit_fsize = None

        if parser.has_option(section, "rlimit_as"):
            rlimit_as = parser.getint(section, "rlimit_as")
        if parser.has_option(section, "rlimit_nofile"):
            rlimit_nofile = parser.getint(section, "rlimit_nofile")
        if parser.has_option(section, "rlimit_nproc"):
            rlimit_nproc = parser.getint(section, "rlimit_nproc")
        if parser.has_option(section, "rlimit_stack"):
            rlimit_stack = parser.getint(section, "rlimit_stack")
        if parser.has_option(section, "rlimit_core"):
            rlimit_core = parser.getint(section, "rlimit_core")
        if parser.has_option(section, "rlimit_fsize"):
            rlimit_fsize = parser.getint(section, "rlimit_fsize")

        output.append("")
        output.append("[watcher:app.%s.%s]" % (plugin_name, app))
        output.append("cmd = plugin_wrapper")

        if typ in PYTHON_TYP_LIST:
            bind = "unix:{{MODULE_RUNTIME_HOME}}/var/" \
                "gunicorn_app_%s_%s.socket" % (plugin_name, app)

            if typ == "gunicorn3_asyncio":
                worker_class = "aiohttp.worker.GunicornWebWorker"
            else:
                worker_class = "sync"
            layer_wrapper_extra_args = plugin_name
            if not add_plugin_dir_to_python_path:
                layer_wrapper_extra_args = layer_wrapper_extra_args + \
                    " --do-not-add-plugin-dir-to-python-path"
            app_dir = os.path.join(plugin_dir, app)
            if add_app_dir_to_python_path:
                layer_wrapper_extra_args = layer_wrapper_extra_args + \
                    " --add-extra-dir-to-python-path=%s" % app_dir
            output.append("args = %s -- "
                          "gunicorn --workers=%s "
                          "--logger-class=gunicorn_custom_log.CustomLogger "
                          "--access-logfile=- --bind=%s --worker-class=%s "
                          "--log-level=%s %s" %
                          (layer_wrapper_extra_args, workers,
                           bind, worker_class, gunicorn_log_level,
                           gunicorn_arg))
            # we force 1 here because gunicorn master deals with x workers
            output.append("numprocesses = %i" % 1)

        elif typ in JS_TYP_LIST:
            bind = "{{MODULE_RUNTIME_HOME}}/var/" \
                "node_%s_$(circus.wid).socket" % (plugin_name,)

            layer_wrapper_extra_args = plugin_name
            if not add_plugin_dir_to_node_path:
                layer_wrapper_extra_args = layer_wrapper_extra_args + \
                    " --do-not-add-plugin-dir-to-node-path"
            app_dir = os.path.join(plugin_dir, app)
            if add_app_dir_to_node_path:
                layer_wrapper_extra_args = layer_wrapper_extra_args + \
                    " --add-extra-dir-to-node-path=%s" % app_dir

            node_server = "%s/%s/%s" % (plugin_dir, app, node_arg)

            output.append("args = %s -- "
                          "node %s %s" %
                          (layer_wrapper_extra_args, node_server, bind))
            output.append("numprocesses = %s" % workers)

        workdir = os.path.join(MFSERV_PLUGINS_HOME, plugin_name)
        output.append("working_dir = %s" % workdir)
        output.append("copy_env = True")
        output.append("async_kill = True")
        output.append("autostart = True")
        output.append("respawn = True")
        if rlimit_as:
            output.append("rlimit_as = %i" % rlimit_as)
        if rlimit_nofile:
            output.append("rlimit_nofile = %i" % rlimit_nofile)
        if rlimit_nproc:
            output.append("rlimit_nproc = %i" % rlimit_nproc)
        if rlimit_stack:
            output.append("rlimit_stack = %i" % rlimit_stack)
        if rlimit_core:
            output.append("rlimit_core = %i" % rlimit_core)
        if rlimit_fsize:
            output.append("rlimit_fsize = %i" % rlimit_fsize)
        output.append("stdout_stream.class = FileStream")
        output.append("stderr_stream.class = FileStream")
        output.append("stdout_stream.filename = "
                      "{{MODULE_RUNTIME_HOME}}/log/"
                      "app_%s_%s.stdout" % (plugin_name, app))
        output.append("stderr_stream.filename = "
                      "{{MODULE_RUNTIME_HOME}}/log/"
                      "app_%s_%s.stderr" % (plugin_name, app))
    if redis_service:
        output.append("")
        output.append("[watcher:redis_service_for_plugin_%s]" % plugin_name)
        output.append("cmd = redis-server")
        output.append("args = {{MODULE_RUNTIME_HOME}}/tmp/config_auto/"
                      "redis_plugin_%s.conf" % plugin_name)
        output.append("numprocesses = 1")
        output.append("stdout_stream.class = FileStream")
        output.append("stdout_stream.filename = {{MODULE_RUNTIME_HOME}}/log/"
                      "redis_plugin_%s.log" % plugin_name)
        output.append("stderr.class = FileStream")
        output.append("stderr.filename = {{MODULE_RUNTIME_HOME}}/log/"
                      "redis_plugin_%s.log" % plugin_name)
        output.append("copy_env = True")
        output.append("autostart = True")
        output.append("respawn = True")
        with open("%s/tmp/config_auto/redis_plugin_%s.conf" %
                  (MODULE_RUNTIME_HOME, plugin_name), "w+") as f:
            with open("%s/config/redis_plugin_xxx.conf" % MODULE_HOME,
                      "r") as f2:
                content = f2.read()
            new_content = envtpl.render_string(content,
                                               {"PLUGIN_NAME": plugin_name})
            f.write(new_content)
    for extra_daemon in extra_daemons:
        section = "extra_daemon_%s" % extra_daemon
        cmd_and_args = parser.get(section, "cmd_and_args")
        numprocesses = parser.getint(section, "numprocesses")
        output.append("")
        output.append("[watcher:extra_daemon_%s_for_plugin_%s]" %
                      (extra_daemon, plugin_name))
        output.append("cmd = plugin_wrapper")
        output.append("args = %s -- %s" % (plugin_name, cmd_and_args))
        output.append("working_dir = %s" % plugin_dir)
        output.append("numprocesses = %i" % numprocesses)
        output.append("copy_env = True")
        output.append("async_kill = True")
        output.append("autostart = True")
        output.append("respawn = True")
        output.append("stdout_stream.class = FileStream")
        output.append("stdout_stream.filename = {{MODULE_RUNTIME_HOME}}/log/"
                      "extra_daemon_%s_plugin_%s.log" %
                      (extra_daemon, plugin_name))
        output.append("stderr.class = FileStream")
        output.append("stderr_stream.filename = {{MODULE_RUNTIME_HOME}}/log/"
                      "extra_daemon_%s_plugin_%s.log" %
                      (extra_daemon, plugin_name))
        rlimit_as = None
        rlimit_nofile = None
        rlimit_nproc = None
        rlimit_stack = None
        rlimit_core = None
        rlimit_fsize = None
        if parser.has_option(section, "rlimit_as"):
            rlimit_as = parser.getint(section, "rlimit_as")
        if parser.has_option(section, "rlimit_nofile"):
            rlimit_nofile = parser.getint(section, "rlimit_nofile")
        if parser.has_option(section, "rlimit_nproc"):
            rlimit_nproc = parser.getint(section, "rlimit_nproc")
        if parser.has_option(section, "rlimit_stack"):
            rlimit_stack = parser.getint(section, "rlimit_stack")
        if parser.has_option(section, "rlimit_core"):
            rlimit_core = parser.getint(section, "rlimit_core")
        if parser.has_option(section, "rlimit_fsize"):
            rlimit_fsize = parser.getint(section, "rlimit_fsize")
        if rlimit_as:
            output.append("rlimit_as = %i" % rlimit_as)
        if rlimit_nofile:
            output.append("rlimit_nofile = %i" % rlimit_nofile)
        if rlimit_nproc:
            output.append("rlimit_nproc = %i" % rlimit_nproc)
        if rlimit_stack:
            output.append("rlimit_stack = %i" % rlimit_stack)
        if rlimit_core:
            output.append("rlimit_core = %i" % rlimit_core)
        if rlimit_fsize:
            output.append("rlimit_fsize = %i" % rlimit_fsize)
    return envtpl.render_string("\n".join(output))


circus_ini_file = os.path.join(os.environ['MODULE_HOME'], 'config',
                               'circus.ini')
with open(circus_ini_file, "r") as f:
    content = envtpl.render_string(f.read())

for config_file in glob.glob(MFSERV_PLUGINS_HOME + "/*/config.ini"):
    content = content + make_watcher_conf(config_file)

print(content)
