#!/bin/bash

set -eu

TMPFILE="${MODULE_RUNTIME_HOME}/tmp/nginx_conf.$$"

UUID=$(cat "${MODULE_RUNTIME_HOME}/var/uuid" 2>/dev/null)
if test "${UUID}" = ""; then
    UUID="unknown"
fi
export UUID

__make_nginx_conf >"${TMPFILE}"
nginxfmt.py "${TMPFILE}"
# FIXME: ugly hack to circumvent nginxfmt problem with JSON
cat -s "${TMPFILE}" |sed 's/~~~1/{/g' |sed 's/~~~2/}/g' |grep -v 'FIXME: ugly hack'

rm -f "${TMPFILE}"
