#!/bin/bash

export MFMODULE_RUNTIME_GROUP=metwork
export PHPFPMCONF=${MFMODULE_RUNTIME_HOME}/tmp/config_auto/php-fpm."$1".conf
export WWWCONF=${MFMODULE_RUNTIME_HOME}/tmp/config_auto/www."$1".conf
export PHP_SOCKET_PATH="$3"
export PHP_LOGFILE_PATH=${MFMODULE_RUNTIME_HOME}/log/app_"$1"_"$2".log

cat ${MFEXT_HOME}/opt/php/etc/php-fpm.conf | envtpl > "${PHPFPMCONF}"
cat ${MFEXT_HOME}/opt/php/etc/php-fpm.d/www.conf | envtpl > ${WWWCONF}

exec ${MFEXT_HOME}/opt/php/sbin/php-fpm --nodaemonize --force-stderr --fpm-config="${PHPFPMCONF}"

